syms I_xx I_xy I_xz I_yy I_yz I_zz...
  psi dpsi ddpsi ...
  th dth ddth  ...
  phi dphi ddphi;

s_theta = sin(th);
c_theta = cos(th);
s_psi = sin(psi);
c_psi = cos(psi);
s_phi = sin(phi);
c_phi = cos(phi);

omega_x = -dpsi*s_theta + dphi;
omega_y = dpsi*c_theta*s_phi + dth*c_phi;
omega_z = dpsi*c_theta*c_phi - dth*s_phi;

domega_x = -ddpsi*s_theta - dpsi*c_theta*dth + ddphi;
domega_y = ddpsi*c_theta*s_phi - dpsi*s_theta*s_phi*dth + ...
  dpsi*c_theta*c_phi*dphi + ddth*c_phi - dth*s_phi*dphi;
domega_z = ddpsi*c_theta*c_phi -dpsi*s_theta*c_phi*dth  - ...
  dpsi*c_theta*s_phi*dphi - ddth*s_phi - dth*c_phi*dphi;

eom1 = collect(expand(I_xx*domega_x - I_xy*(domega_y - omega_x*omega_z) - ...
  I_xz*(domega_z + omega_x*omega_y) - ...
  (I_yy - I_zz)*omega_y*omega_z - I_yz*(omega_y^2 - omega_z^2)), ...
  [ddpsi, ddphi, ddth, dpsi, dphi, dth]);

eom2 = collect(expand(I_yy*domega_y - I_yz*(domega_z - omega_x*omega_y) - ...
  I_xy*(domega_x + omega_y*omega_z) - ...
  (I_zz - I_xx)*omega_x*omega_z - I_xz*(omega_z^2 - omega_x^2)), ...
  [ddpsi, ddphi, ddth, dpsi, dphi, dth]);

eom3 = collect(expand(I_zz*domega_z - I_xz*(domega_x - omega_y*omega_z) - ...
  I_yz*(domega_y + omega_x*omega_z) - ...
  (I_xx - I_yy)*omega_x*omega_y - I_xy*(omega_x^2 - omega_y^2)), ...
  [ddpsi, ddphi, ddth, dpsi, dphi, dth]);
